# Poznámky

Kapitola 3
## Chi-kvadrát
## Jak vybrat rozložení

```{r, message=FALSE, warning=FALSE}
library(leaflet)
```

```{r}
v2_location <- read.csv("../dats/v2_location.csv")
v2_location <- v2_location[complete.cases(v2_location), ]
v2_location$label <- paste(paste(v2_location$landing_site, v2_location$date, sep = ", "))

v2_location$lat <- v2_location$lat + rnorm(nrow(v2_location), 0, 0.01)
v2_location$lon <- v2_location$lon + rnorm(nrow(v2_location), 0, 0.05)
# greater london area
mu <- c(51.5072178, -0.1275862)
lon <- c(-0.492267, 0.362430)
lat <- c(51.274614, 51.73982)

# index
i <- (v2_location$lat >= lat[1] & v2_location$lat <= lat[2]) & (
  v2_location$lon >= lon[1] & v2_location$lon <= lon[2]
)

v2_london <- v2_location[i, ]

leaflet(data = v2_london) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addCircleMarkers(
    lng = ~lon,
    lat = ~lat, color = "#000000",
    opacity = 0.2,
    fillOpacity = 0.2,
    fillColor = "#000000",
    radius = 2.5,
    stroke = FALSE,
    label = ~label
  )
```

```{r}
# simulujeme nemoznost mireni
n <- nrow(v2_london)
v2_uni <- data.frame(
  lon = runif(
    n = n,
    min = lon[1],
    max = lon[2]
  ),
  lat = runif(
    n = n,
    min = lat[1],
    max = lat[2]
  )
)

v2_norm <- data.frame(
  lon = rnorm(
    n = n,
    mean = mean(v2_london$lon),
    sd = sd(v2_london$lon)
  ),
  lat = rnorm(
    n = n,
    mean = mean(v2_london$lat),
    sd = sd(v2_london$lat)
  )
)

fig <- leaflet(data = v2_london) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addCircleMarkers(
    lng = ~lon,
    lat = ~lat, color = "#000000",
    opacity = 0.2,
    fillOpacity = 0.2,
    fillColor = "#000000",
    radius = 2.5,
    stroke = FALSE,
    label = ~label
  )

fig <- addCircleMarkers(
  map = fig,
  lng = v2_norm$lon,
  lat = v2_norm$lat, color = "#1f77b4",
  opacity = 0.2,
  fillOpacity = 0.2,
  fillColor = "",
  radius = 2.5,
  stroke = FALSE,
  label = "Uniform"
)
fig
```

Přidat multivariate normal kdyžese bude probírat covariance.


Model Země

```{r, fig.cap='Model Země', fig.align='center', echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)

df <- read.csv("https://raw.githubusercontent.com/plotly/datasets/master/globe_contours.csv")
df$id <- seq_len(nrow(df))

library(tidyr)
d <- df %>%
  gather(key, value, -id) %>%
  separate(key, c("l", "line"), "\\.") %>%
  spread(l, value)

geo <- list(
  showland = TRUE,
  showlakes = TRUE,
  showcountries = TRUE,
  showocean = TRUE,
  countrywidth = 0.5,
  landcolor = "rgb(230, 145, 56)",
  lakecolor = "rgb(0, 255, 255)",
  oceancolor = "rgb(0, 255, 255)",
  projection = list(
    type = "orthographic",
    rotation = list(
      lon = -100,
      lat = 40,
      roll = 0
    )
  ),
  lonaxis = list(
    showgrid = TRUE,
    gridcolor = toRGB("gray40"),
    gridwidth = 0.5
  ),
  lataxis = list(
    showgrid = TRUE,
    gridcolor = toRGB("gray40"),
    gridwidth = 0.5
  )
)


# sliders
lon_range <- data.frame(seq(-180, 180, 10))
lat_range <- data.frame(seq(-90, 90, 10))
colnames(lon_range) <- "x"
colnames(lat_range) <- "x"

all_lat <- list()
for (i in 1:length(lat_range[, ])) {
  all_lat[[i]] <- list(
    method = "relayout",
    args = list(list(geo.projection.rotation.lat = lat_range$x[i])),
    label = lat_range$x[i]
  )
}

all_lon <- list()
for (i in 1:length(lon_range[, ])) {
  all_lon[[i]] <- list(
    method = "relayout",
    args = list(list(geo.projection.rotation.lon = lon_range$x[i])),
    label = lon_range$x[i]
  )
}


# original d3-globe with contours
fig <- plot_geo(d)
fig <- fig %>% layout(
  showlegend = FALSE, geo = geo
)

# plot with custom events
fig <- fig
fig <- fig %>% layout(sliders = list(
  list(
    active = (length(lon_range[, ]) - 1) / 2,
    currentvalue = list(prefix = "Longitude: "),
    pad = list(t = 20),
    steps = all_lon
  ),
  list(
    active = (length(lat_range[, ]) - 1) / 2,
    currentvalue = list(prefix = "Latitude: "),
    pad = list(t = 100),
    steps = all_lat
  )
))

fig
```